name:                fuzzy-dates-megaparsec
version:             0.1.1.3
github:              "nitros12/fuzzy-dates-megaparsec"
license:             BSD3
author:              "Reed Oei, Ben Simms"
maintainer:          "oei.reed@gmail.com"
copyright:           "2018 Reed Oei"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Libary for parsing dates in strings in varied formats.
category:            Parsing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ReedOei/fuzzy-dates#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 8.0 && < 10.0
- case-insensitive ^>= 1.2
- hourglass ^>= 0.2
- lens >= 4.18
- hspec ^>= 2.7

library:
  source-dirs: src

tests:
  fuzzy-dates-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fuzzy-dates-megaparsec
